config/routes.rb
ContactsKeeper::Application.routes.draw do

  root to: 'home#index'
  devise_for :users, controllers: {registrations: 'registrations'}
  resources :users, only: [:index, :show, :update, :destroy]
  #resources :contacts_backups, except: [:show, :new, :create, :edit] do
  resources :contacts_backups, only: [:index, :destroy] do
    patch :set_actual, on: :member
  end

  mount API => '/'

end

app/models/contacts_backup.rb
class ContactsBackup < ActiveRecord::Base
  scope :by_created_desc, -> { order('contacts_backups.created_at desc') }
  scope :actual, -> { where(is_actual: true) }
  belongs_to :user
  delegate :name, to: :user, prefix: true, allow_nil: true
  validates_presence_of :name, :phone, :data, :user, :system
  validates_uniqueness_of :is_actual, scope: :user_id, if: Proc.new { |b| b.is_actual }
  before_save :clear_actual, :set_actual

  def self.search(params)
    contacts_backups = ContactsBackup.all

    if (q = params[:q]).present?
      contacts_backups = contacts_backups.where ["lower(contacts_backups.name) LIKE :value OR lower(contacts_backups.phone) LIKE :value", { value: "%#{q.mb_chars.downcase.to_s}%" }]
    end

    if (user_q = params[:user_q]).present?
      contacts_backups = contacts_backups.includes(:user).where ["lower(users.name) LIKE :value OR lower(users.email) LIKE :value", { value: "%#{user_q.mb_chars.downcase.to_s}%" }]
    end

    contacts_backups
  end

  private

  def clear_actual
    self.user.contacts_backups(true).actual.each { |b| b.update_column(:is_actual, false) }
  end

  def set_actual
    self.is_actual = true
  end

end

app/controllers/contacts_backups_controller.rb
class ContactsBackupsController < ApplicationController
  before_action :set_contacts_backup, only: [:show, :edit, :update, :destroy, :set_actual]
  authorize_resource

  def index
    @contacts_backups = current_user.is_admin? ? ContactsBackup.all : current_user.contacts_backups.actual
    @contacts_backups = @contacts_backups.search(params).by_created_desc.page params[:page]
    respond_to do |format|
      format.html
      format.js { render 'shared/index' }
    end
  end

  #def edit
  #end

  #def update
  #  respond_to do |format|
  #    if @contacts_backup.update(contacts_backup_params)
  #      format.html { redirect_to contacts_backups_path, notice: 'Contacts backup was successfully updated.' }
  #      format.json { head :no_content }
  #    else
  #      format.html { render action: 'edit' }
  #      format.json { render json: @contacts_backup.errors, status: :unprocessable_entity }
  #    end
  #  end
  #end

  def destroy
    @contacts_backup.destroy
    respond_to do |format|
      format.html { redirect_to contacts_backups_url }
    end
  end

  def set_actual
    @contacts_backup.update_attribute :is_actual, true
    @contacts_backups = @contacts_backup.user.contacts_backups(true)
    respond_to do |format|
      format.js
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_contacts_backup
    @contacts_backup = ContactsBackup.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def contacts_backup_params
    params.require(:contacts_backup).permit(:is_actual, :name, :phone, :data)
  end

end

app/helpers/contacts_backups_helper.rb
module ContactsBackupsHelper
end

app/views/contacts_backups/_contacts_backup.html.haml
%tr{class: contacts_backup.is_actual ? 'success' : ''}[contacts_backup]
  %td= contacts_backup.user_name
  %td= contacts_backup.name
  %td= contacts_backup.phone
  %td= l contacts_backup.created_at, format: :long
  - if can? :manage, ContactsBackup
    %td.actions
      .btn-group.btn-group-xs
        = link_to glyph(:ok), set_actual_contacts_backup_path(contacts_backup), method: :patch, remote: true, class: 'btn btn-default', title: t('contacts_backups.table.set_actual'), data: {toggle: :tooltip, placement: :left, container: 'body'} unless contacts_backup.is_actual
        = link_to glyph(:trash), contacts_backup, method: :delete, data: {confirm: t(:confirmation), toggle: :tooltip, placement: :left, container: 'body'}, class: 'btn btn-danger', title: t('contacts_backups.table.delete')

app/views/contacts_backups/_form.html.haml
= form_for @contacts_backup, html: {class: 'form-horizontal', role: 'form'} do |f|

  .form-group{class: f.object.errors[:is_actual].present? ? 'has-error' : ''}
    .col-sm-offset-2.col-sm-6
      .checkbox
        %label
          = f.check_box :is_actual
          = ContactsBackup.human_attribute_name :is_actual
      - if f.object.errors[:is_actual]
        %span.help-block= f.object.errors[:is_actual].join ', '

  .form-group{class: f.object.errors[:name].present? ? 'has-error' : ''}
    = f.label :name, class: 'col-sm-2 control-label'
    .col-sm-6
      = f.text_field :name, class: 'form-control'
      - if f.object.errors[:name]
        %span.help-block= f.object.errors[:name].join ', '

  .form-group{class: f.object.errors[:phone].present? ? 'has-error' : ''}
    = f.label :phone, class: 'col-sm-2 control-label'
    .col-sm-6
      = f.text_field :phone, class: 'form-control'
      - if f.object.errors[:phone]
        %span.help-block= f.object.errors[:phone].join ', '

  .form-group
    .col-sm-offset-2.col-sm-6= f.submit class: 'btn btn-primary'

app/views/contacts_backups/_table.html.haml
- model_class = ContactsBackup
.resource_table
  %table#contacts_backups_table.table.table-hover
    %thead
      %tr
        %th= model_class.human_attribute_name :user
        %th= model_class.human_attribute_name :name
        %th= model_class.human_attribute_name :phone
        %th= model_class.human_attribute_name :created_at
        - if can? :manage, ContactsBackup
          %th.actions
    %tbody
      = render @contacts_backups

  = paginate @contacts_backups, remote: true

app/views/contacts_backups/edit.html.haml
%h1= t '.title'
= render 'form'

app/views/contacts_backups/index.html.haml
.page-header
  %h3= t '.title'

- if can? :manage, ContactsBackup
  .panel.panel-default
    .panel-heading
      = form_tag contacts_backups_path, method: :get, id: 'search_form', class: 'form-inline', remote: true do
        .row
          .form-group.col-xs-4.col-md-4
            .input-group
              -#%span.input-group-addon= glyph(:search)
              %span.input-group-btn
                %button.btn.btn-info{type: 'submit'}= glyph(:search)
              = text_field_tag :q, params[:q], class: 'form-control', placeholder: t('.search_placeholder')
              %span.input-group-btn
                %button.btn.btn-default.clear_search_input{type: 'button'}= glyph(:remove)

          .form-group.col-xs-4.col-md-4
            .input-group
              -#%span.input-group-addon= glyph(:search)
              %span.input-group-btn
                %button.btn.btn-info{type: 'submit'}= glyph(:search)
              = text_field_tag :user_q, params[:user_q], class: 'form-control', placeholder: t('.user_search_placeholder')
              %span.input-group-btn
                %button.btn.btn-default.clear_search_input{type: 'button'}= glyph(:remove)

= render 'table'

app/views/contacts_backups/new.html.haml
%h1 New contacts_backup

= render 'form'

= link_to 'Back', contacts_backups_path

app/views/contacts_backups/set_actual.js.haml
:plain
  removeTooltips();
- @contacts_backups.each do |contacts_backup|
  :plain
    $("#contacts_backup_#{contacts_backup.id}").replaceWith("#{j(render(contacts_backup))}");

app/views/contacts_backups/show.html.haml
%p#notice= notice

%p
  %b User:
  = @contacts_backup.user
%p
  %b Name:
  = @contacts_backup.name
%p
  %b Phone:
  = @contacts_backup.phone

= link_to 'Edit', edit_contacts_backup_path(@contacts_backup)
\|
= link_to 'Back', contacts_backups_path