config/routes.rb
ContactsKeeper::Application.routes.draw do

  root to: 'home#index'
  devise_for :users, controllers: {registrations: 'registrations'}
  resources :users, only: [:index, :show, :update, :destroy]
  #resources :contacts_backups, except: [:show, :new, :create, :edit] do
  resources :contacts_backups, only: [:index, :destroy] do
    patch :set_actual, on: :member
  end

  mount API => '/'

end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :registerable#, :confirmable
  cattr_accessor :current
  attr_accessor :login
  validates :name, uniqueness: {case_sensitive: false}, presence: true, length: {minimum: 4}
  before_save :generate_api_password

  has_many :contacts_backups, dependent: :destroy

  def actual_contacts_backup
    contacts_backups.actual.first
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(name) = :value OR lower(email) = :value", { value: login.mb_chars.downcase.to_s }]).first
    else
      where(conditions).first
    end
  end

  def self.search(params)
    users = User.all
    if (q = params[:q]).present?
      users = users.where ["lower(name) LIKE :value OR lower(email) LIKE :value", { value: "%#{q.mb_chars.downcase.to_s}%" }]
    end
    users
  end

  private

  def generate_api_password
    self.api_password = Digest::MD5.hexdigest [self.name, API::REALM, self.password]*':' unless self.password.blank?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  authorize_resource

  def index
    #authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all.search(params).page params[:page]
    respond_to do |format|
      format.html
      format.js { render 'shared/index' }
    end
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    #authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)#, as: :admin)
      redirect_to users_path, notice: "User updated."
    else
      redirect_to users_path, alert: "Unable to update user."
    end
  end

  def destroy
    #authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, notice: "User deleted."
    else
      redirect_to users_path, notice: "Can't delete yourself."
    end
  end

  private

  def user_params
    params.require(:user).permit(:role_ids)
  end

end

app/views/users/_table.html.haml
.resource_table
  %table#users_table.resource_table.table.table-hover
    %thead
      %tr
        %th= User.human_attribute_name :name
        %th= User.human_attribute_name :email
        %th= User.human_attribute_name :created_at
        %th= User.human_attribute_name :role
        %th.actions
    %tbody
      - @users.each do |user|
        %tr
          %td= link_to user.name, user
          %td= link_to user.email, user
          %td= l user.created_at, format: :long
          %td= user.roles.first.name.titleize unless user.roles.first.nil?
          %td.actions
            = render user
            .btn-group.btn-group-xs
              %button.btn.btn-default{data: {toggle: 'modal', target: "#role-options-#{user.id}"}}= glyph(:edit)
              = link_to glyph(:trash), user_path(user), data: {confirm: t(:confirmation), toggle: :tooltip, placement: :left, container: 'body'}, method: :delete, class: 'btn btn-danger', title: t('.delete') unless user == current_user
  = paginate @users, remote: true

app/views/users/_user.html.haml
.modal.fade{id: "role-options-#{user.id}"}
  .modal-dialog
    .modal-content
      = simple_form_for user, url: user_path(user), html: {method: :put, class: 'form-horizontal' } do |f|
        .modal-header
          %a.close{"data-dismiss" => "modal", "aria-hidden" => true} &times;
          %h4.modal-title= t 'users.table.change_role'
        .modal-body
          = f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first
        .modal-footer
          = f.submit t('users.table.change_role'), class: "submit"

app/views/users/index.html.haml
.page-header
  %h3= t '.title'

.panel.panel-default
  .panel-heading
    = form_tag users_path, method: :get, id: 'search_form', class: 'form-inline', remote: true do
      .row
        .form-group.col-xs-4.col-md-4
          .input-group
            -#%span.input-group-addon= glyph(:search)
            %span.input-group-btn
              %button.btn.btn-info{type: 'submit'}= glyph(:search)
            = text_field_tag :q, params[:q], class: 'form-control', placeholder: t('.search_placeholder')
            %span.input-group-btn
              %button.btn.btn-default.clear_search_input{type: 'button'}= glyph(:remove)

= render 'table'

app/views/users/show.html.haml
.page-header
  %h3= t '.title'

%dl.dl-horizontal
  %dt= User.human_attribute_name :name
  %dd= @user.name

  %dt= User.human_attribute_name :email
  %dd= @user.email

  - if current_user.is_admin?
    %dt= User.human_attribute_name :roles
    %dd= @user.roles.any? ? @user.roles.map{|r| r.name.titleize}.join(', ') : '-'