config/routes.rb
ContactsKeeper::Application.routes.draw do

  root to: 'home#index'
  devise_for :users, controllers: {registrations: 'registrations'}
  resources :users, only: [:index, :show, :update, :destroy]
  #resources :contacts_backups, except: [:show, :new, :create, :edit] do
  resources :contacts_backups, only: [:index, :destroy] do
    patch :set_actual, on: :member
  end

  mount API => '/'

end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "danger"}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to glyph(:home), root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
- if user_signed_in?
  = menu_item t('.contacts_backups'), contacts_backups_path if can? :manage, ContactsBackup
  - if current_user.is_admin?
    = menu_item t('.users'), users_path
  -#= menu_item current_user.name, edit_user_registration_path
  = menu_item t('.logout'), destroy_user_session_path, method: 'delete'
- else
  = menu_item t('.login'), new_user_session_path
  -#= menu_item t('.sign_up'), new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Contacts Keeper'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Contacts Keeper'}"}
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main.container-fluid{role: "main"}
      = render 'layouts/messages'
      = yield